apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: pivauths.chrisruffalo.github.com
spec:
  group: chrisruffalo.github.com
  names:
    kind: PivAuth
    listKind: PivAuthList
    plural: pivauths
    singular: pivauth
  scope: Namespaced
  version: v1alpha1
  subresources:
    status: {}