---
- hosts: 
  - localhost
  vars:
    # default to deploying 1 pod
    size: 1
    # use rhel7 as the default deployment
    flavor: rhel7
    # enable rhcsl to allow for newer httpd version deployment
    rhcsl: false
  tasks:
  # show vars
  - debug:
      var: hostvars[inventory_hostname]
  - debug:
      var: meta

  # assert required spec fields are available
  - fail:
      msg: "No smartcard_ca field provided on PivAuth: {{ meta.name }}"
    when: smartcard_ca is not defined

  # create the shared secrets that authenticate the proxy back
  # to the authentication provider (with two-way ssl and host verification)
  - include_tasks: tasks/create_auth_provider_shared_secrets.yml

  # create the secret to hold the smartcard
  - include_tasks: tasks/create_smartcard_ca_secret.yml


