---
- hosts: 
  - localhost
  tasks:
  # assert required spec fields are available
  - fail:
      msg: "No smartcard_ca field provided on PivAuth: {{ metadata.name }}"
    when: not defined smartcard_ca

  # create the shared secrets that authenticate the proxy back
  # to the authentication provider (with two-way ssl and host verification)
  - include_tasks: tasks/create_auth_provider_shared_secrets.yml

  # create the secret to hold the smartcard
  - include_tasks: tasks/create_smartcard_ca_secret.yml


