---
- hosts: 
  - localhost
  vars:
    # namespace from meta namespace
    namespace: "{{ namespace | default(meta.namespace) }}"
    # default to deploying 1 pod
    size: 1
    # use rhel as the default deployment
    flavor: rhel
    # enable rhcsl to allow for newer httpd version deployment
    rhcsl: false
    # git, todo: move into this repo and make better use of variables
    ose_pivproxy_git: "https://github.com/RedHatOfficial/ose-pivproxy.git"
  tasks:
  # assert required spec fields are available
  - fail:
      msg: "No smartcard_ca field provided on PivAuth: {{ meta.name }}"
    when: smartcard_ca is not defined

  # require external url

  # create the shared secrets that authenticate the proxy back
  # to the authentication provider (with two-way ssl and host verification)
  - include_tasks: tasks/create_auth_provider_shared_secrets.yml

  # create the secret to hold the smartcard
  - include_tasks: tasks/create_smartcard_ca_secret.yml

  # build configuration for the httpd proxy container
  - include_tasks: tasks/create_pivproxy_build_config.yml

  # create the deployment configuration
  - include_tasks: tasks/create_deployment_configuration.yml

  # inject the identity provider into the master



