---
- name: Create a Secret from a given spec value
  k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "{{ meta.name }}-pivauth-smartcard-ca"
        namespace: "{{ namespace }}"
        labels:
          app: "{{ meta.name }}-pivauth"
      type: opaque
      data:
        "smartcard-ca.crt": "{{ smartcard_ca | b64encode }}"

