---
- name: Create shared signer certificate
  command: "oc adm ca create-signer-cert --cert=/tmp/proxyca.crt --key=/tmp/proxyca.key --name='openshift-proxy-signer@`date +%s`' --serial=/tmp/proxyca.serial.txt"

- nane: Create api config for shared secret
  command: "oc adm create-api-client-config --certificate-authority=/tmp/proxyca.crt --client-dir=/tmp --signer-cert=/tmp/proxyca.crt --signer-key=/tmp/proxyca.key --signer-serial=/tmp/proxyca.serial.txt --user='system:proxy'"

- name: Create certificate bundle
  command: "cat /tmp/system\:proxy.crt /tmp/system\:proxy.key > /tmp/piv_proxy.pem"

