---
- name: Create a Secret from a given spec value
  k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: pivauth-smartcard-ca
        labels:
          app: pivauth
      type: opaque
      data:
        "smartcard-ca.crt": "{{ spec.smartcard_ca }}"

