apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: pivauth-operator
  namespace: openshift-console
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - 'get'
  - 'list'
- apiGroups:
  - "route.openshift.io"
  resources:
  - routes
  verbs:
  - 'get'
  - 'list'