apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: pivauth-operator
  namespace: openshift-config
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  - oauths
  verbs:
  - '*'