apiVersion: apps/v1
kind: Deployment
metadata:
  name: pivauth-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: pivauth-operator
  template:
    metadata:
      labels:
        name: pivauth-operator
    spec:
      serviceAccountName: pivauth-operator
      containers:
        - name: pivauth-operator
          # Replace this with the built image name
          image: quay.io/cruffalo/ansible-pivauth-operator:latest
          imagePullPolicy: Always
          env:
            - name: 
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: OPERATOR_NAME
              value: "pivauth-operator"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name