apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: pivauth-operator
  namespace: ansible-pivauth-operator
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - '*'
- apiGroups:
  - "image.openshift.io"
  resources:
  - imagestreams
  - imagestreamtags
  verbs:
  - '*'
- apiGroups:
  - "route.openshift.io"
  resources:
  - routes
  verbs:
  - '*'
- apiGroups:
  - "build.openshift.io"
  resources:
  - buildconfigs
  - buildconfigs/instantiate
  - builds
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - chrisruffalo.github.com
  resources:
  - '*'
  verbs:
  - '*'